[tasks.clean]
confirm = "Are youn sure?"
description = "Clean up"
run = "cargo clean"

[tasks.update]
confirm = "Are youn sure?"
description = "Update dependencies"
run = "cargo update"

[tasks.test]
description = "Run a test"
run = "cargo test"

[tasks.bench]
description = "Run a benchmark"
run = "cargo run -p comptest --release"

[tasks.flamegraph]
description = "Generate flamegraph"
run = "cargo flamegraph -p comptest"
